# Generated by Django 4.1 on 2022-08-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PessoasCrud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
