# Generated by Django 4.1 on 2022-08-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PessoasCrud', '0003_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='idade',
            new_name='ano_nascimento',
        ),
    ]
