# Generated by Django 4.1 on 2022-08-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PessoasCrud', '0005_rename_ano_nascimento_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True),
        ),
    ]
