# Generated by Django 4.1 on 2022-09-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PessoasCrud', '0007_alter_pessoa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='nome',
            new_name='bairro',
        ),
        migrations.AddField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
